### PR TITLE
added cascading on delete to UserNotification Entity

### PR DESCRIPTION
**Pull request by skandertebo**

### CODE REVIEW

**Review by MohamedRebai41 — COMMENTED** [review]
What groups of users do you have in mind? Is it a column in the users entity or is it an entire entity with users having multiple groups?

**Comment by skandertebo** [comment]
> What groups of users do you have in mind? Is it a column in the users entity or is it an entire entity with users having multiple groups?

it's a text column in the notification entity, for now a very simple example is that if it is set to '*', this means that the notification concerns all users, this is much more performant than creating a relation for all users

**Comment by skandertebo** [comment]
> What groups of users do you have in mind? Is it a column in the users entity or is it an entire entity with users having multiple groups?

do not merge, the attribute is_read forces the idea to have a user_notification entity for any user and any notification, wait on this pr until further notice

**Comment by skandertebo** [comment]
> > What groups of users do you have in mind? Is it a column in the users entity or is it an entire entity with users having multiple groups?
> 
> do not merge, the attribute is_read forces the idea to have a user_notification entity for any user and any notification, wait on this pr until further notice

you can merge now

**Pull request merged**
